20230410_094152 (update_mon)

diff --git a/linux/shell/command/catalog b/linux/shell/command/catalog
--- a/linux/shell/command/catalog
+++ b/linux/shell/command/catalog
@@ -1,7 +1,8 @@
 #!/usr/bin/env bash  ## search $path for bash
 : '\nmulti\nline\ncode\nblock\n# '  ## switchable multiline codeblock (prepend with #) / comment
+< $file  ## less $file (oxos zshrc)
 < ${$(get_newest_file $XDG_LOGS_HOME/upgrader/$HOST/package_lists/)%?}Q  ## make last character of newest file a Q and print that file (last upgrades)
-< /home/cytopyge/.config/qutebrowser/bookmark_urls | fzf | slicer '(' ')'  ## get from bookmark_urls
+< $XDG_CONFIG_HOME/qutebrowser/bookmark_urls | fzf | slicer '(' ')'  ## get from bookmark_urls
 echo hello 1> $file  ## redirect stdout write to $file
 echo hello 2>> $file   ## redirect stderr append to $file
 echo hello &> /dev/null  ## redirect stdout and stderr write to devnull; silent execution
@@ -32,8 +33,8 @@ cat $HOME/c/keys/wl/ap.wifi | grep '#psk' | awk -F "\"" '{print $2}' | qrencode 
 cat -n <file>  ## line number cat
 cat -vE $file  ## prevent cat shell injection
 cat 0< $file >1 /dev/stdout  ## rudimentary form of: cat $file
-cat <<- EOF >> file\n multi\nline\ntext\nmlt\nEOF\n  ## append mlt to file (heredoc), strip leading tabs from mlt (-), EOF can be any unique limit string
-cat /etc/group  ## list all user groups
+#cat <<- EOF >> file\n multi\nline\ntext\nmlt\nEOF\n  ## append mlt to file (heredoc), strip leading tabs from mlt (-), EOF can be any unique limit string
+< /etc/group  ## list all user groups
 cd $(fd -t d -H -I . $HOME | fzf --preview="tree -L 1 {}" --bind="space:toggle-preview" --preview-window=:hidden)  ## fzf cd from $HOME, spacebar for info box
 cd $HOME/.config/hosts; git switch blocklist_on; cd -  ## activate network blocklist
 cd $XDG_CONFIG_HOME/shln; sh chln; cd .; cd -  ## change symlinks to current $USER for $PATH
@@ -45,6 +46,7 @@ chown -R $USER:$GROUP $target  ## recursive set target ownership to current user
 chown :group file  ## set group ownership
 chown user: file  ## set user ownership
 clear  ## shift current line to top of screen
+cmp $lf $rf  ## byte compare files, boolean output
 cp -prv --attributes-only  ## copy no content, but only mode, ownership and timestamps, verbose
 cp -pv  ## copy and preserve mode, ownership and timestamps, verbose
 cryptsetup --cipher=aes-xts-plain64 -hash=sha512 --key-size=512 --offset=0 --verify-passphrase open --type=plain /dev/sdX lvm
@@ -55,12 +57,11 @@ cryptsetup luksRemoveKey --key-slot 7 $file  ## remove luks key from slot 7 of $
 cryptsetup luksDump file  ## dump header information
 cryptsetup luksChangeKey file  ## change a key
 cryptsetup luksUUID <luks_container> | wl-copy -o -n  ## get luks container id
-cryptsetup open /dev/sdX cryptlvm
+cryptsetup open /dev/sdX cryptlvm  ## open /dev/sdX to cryptlvm
 cryptsetup open /dev/sdX cryptroot --debug  ## which keyslot is used for passphrase
-ctags -R ~/.
 curl $(wl-paste) | zathura -  ## stream a copied (qb ;y) pdf url
-curl -4 https://ident.me	## external ip address
-curl -O https://mirror.i3d.net/pub/archlinux/iso/2018.04.01/archlinux-2018.04.01-x86_64.iso | sudo dd of=/dev/sdX	## download arch linux iso and write to device
+curl -4 https://ident.me  ## external ip address
+curl -O https://mirror.i3d.net/pub/archlinux/iso/2018.04.01/archlinux-2018.04.01-x86_64.iso | sudo dd of=/dev/sdX  ## download arch linux iso and write to device
 cut -d , -f 5 --complement file.csv  ## remove column 5 from file.csv
 date && sudo hwclock --show --verbose  ## read hardware clock time and its drift
 date +%s  ## epoch current date
@@ -70,50 +71,50 @@ dd if=/dev/sdX of=/dev/sdY bs=4M status=progress oflag=sync  ## dd copy sdX to s
 df -h	## file system information human-readable
 dhcpcd -k wlp58s0  ## dhcp remove interface ip
 dhcpcd wlp58s0	## dhcp request for interface
-diff -Naur <lf> <rf> > patch_file  ## recursive diff from lf to rf with 3 lines of context (unified)
+diff --side-by-side --left-column $lf $rf  ## print $lf; $rf diffs in right column (-y --left-column)
+diff --new-file --text --unified=3 --recursive $lf $rf > $patch_file  ## create recursive $patch-file unified with 3 lines of context from $lf to $rf (-Naur)
 diff <(echo $(uname -r | grep --only-matching '[[:digit:]]' | tr -d '[:blank:]\t\r\n')) <(echo $(pacman -Q linux | grep --only-matching '[[:digit:]]' | tr -d '[:blank:]\t\r\n')) | tr -d '\n'  ## check if kernel reboot required
 dig -x 89.39.107.195  ## reverse lookup own public ip
-dirname <filename>  ## print <filename> without last component
-du -sbh <directory>  ## total size of all content in directory
-e2label /dev/X [label]  ## read [/rewrite] device label
+dirname $filename  ## print <filename> without last component
+du -sbh $directory  ## total size of all content in directory
+e2label /dev/X  ## read device label
+e2label /dev/X $label  ## write device label
 echo "obase=02; ibase=16; $(echo $hex | tr a-z A-Z)" | bc  ## bc hexadecimal to binary conversion
 echo "obase=10; ibase=16; $(echo $hex | tr a-z A-Z)" | bc  ## bc hexadecimal to decimal conversion
 echo "obase=16; ibase=10; $dec" | bc  ## bc dec (10) to hex (16) conversion
 echo $(( 1 ^ 2 ))  ## decimal value of xor 1 and 2 (xor 01 and 10 = 11)
 echo -n $string | base64  ## base64 encoding
-echo 0  ## print exit code of the last executed command
+echo $?  ## print exit code of the last executed command
 echo ${USER%??}$string  ## replace last two (%??) characters of $USER by $string
 wl-paste | sed -n '1p' | sed 's/[^0-9]//g' | cut -c 1-4  ## first four digits from multiline string
-wl-paste | grep -Eo '[0-9]' | tail -n 4 | tr -d '[:blank:]\t\r\n'   ## last four digits from multiline string
+wl-paste | grep -Eo '[0-9]' | tail -n 4 | tr -d '[:blank:]\t\r\n'  ## last four digits from multiline string
 emacsclient --daemon[=$server_name]  ## start emacs daemon
 emacsclient -c  ## start emacs client
 emacsclient -e "(kill-emacs)" -s server  ## kill emacs server
 env  ## print current environment variables and their values
-eval $(ssh-agent) && ssh-add $XDG_DATA_HOME/c/keys/ssh/$ssh_key
+eval $(ssh-agent) && ssh-add $XDG_DATA_HOME/c/keys/ssh/$ssh_key  ## concatenate arguments, add ssh_key
 faillock --user $USER --reset  ## remove sudo lockout for current user
 fc  ## edit last command in
 fc -l -n -1  ## last command entered, hide line number
-fc-list  ## list available fonts
+fc-list  ## list available fonts (fontconfig)
 fd -u . | fzf --query=`wl-paste` | wl-copy  ## fzf search wl-paste file path and wl-paste (quick file search)
 ffprobe -i $media_file -show_entries format=duration -v quiet -of csv="p=0" -sexagesimal  ## get $media_file duration (seconds or sexagesimal)
 fg [%n]  ## job [n] to foreground
 fg [id]  ## recall suspended command to foreground
 figlet -f 'mini' oxo  ## figchars
-find . -exec <command> {} \;
-find . -maxdepth 1 -name \*_ -type d -exec cp -r {} ~/test_/bu \;
+find . -exec $command {} \;  ## find exec structure
+find . -maxdepth 1 -name \*_ -type d -exec cp -r {} ~/test_/bu \;  ## find all dirs ending with _ and copy them (NOTICE: '\*_')
 find . -maxdepth 1 -type d -exec du -sb {} \; | sort -g -k 1  ## directories sorted by size (bytes)
 find . -maxdepth 1 -type f -name "* *" -exec sh -c 'mv "$0" "${0// /_}"' {} \;  ## find filenames with spaces and replace with underscore
 find . -maxdepth 1 -type l -exec cp -d {} $HOME/.dot \;  ## find symlinks and copy without dereferencing
-find . -name filename_start__\*
 find . -type f ! -newermt "2018-12-31" -delet3	## find and delete all files older (not newer) than date
 find . -type f -exec mv {} <dest> \;  ## find all files and move them to destination directory
-find . -type l -exec sh -c "file -b {} | grep -q ^broken" \; -print
+find . -type l -exec sh -c "file -b {} | grep -q ^broken" \; -print  ## find broken symbolic links
 find . -xtype l -print
 find ./ -maxdepth 1 -type f -mtime +1 -print
 find / -iname file_case_insensitive
 find /<directory> -name '<search-string>' 2>/dev/null
 find /<directory> -type f -exec shred -v -z -n 3 -u {} \;
-findmnt
 for file in *; do cp -- "$file" "string_$file"; done  ## append string_ to each file in cwd
 for i in {0..255}; do; printf "\x1b[38;5;${i}mcolour${i}\x1b[0m\n"; done  ## print 256 colors
 for i in {1..65535}; do (echo < /dev/tcp/127.0.0.1/$i) &>/dev/null && printf "\n[+] open port\n: \t%d\n" "$i" || printf "$i\r"; done  ## portscan
@@ -125,7 +126,6 @@ getent ahosts <url>  ## get ip address from name service switch library database
 git config --show-scope --show-origin --list  ## origin and scope of git configuration
 git log --oneline  ## list of commits
 git reset --hard 2db93df  ## back to a previous commit
-glances
 gnutls-cli -d 1 grc.com -p 443  ## get certificate info
 gpg --armor --export ID > ID.puk.gpg  ## export public key ascii armored id
 gpg --detach-sign --local-user 0x12345678 $file  ## sign $file with specific secret key
@@ -173,8 +173,8 @@ ip link set dev [interface] address [mac]  ## assign [mac] address to [interface
 ip link set dev [interface] down  ## disconnect from the network by disable interface
 ip n show	## show neighbour / arp cache
 ip link show $enp | grep link | awk '{print $2}'  ## print $enp mac address
-ip route add default via <default_gateway>
-ip route flush dev <interface>
+ip route add default via $default_gateway
+ip route flush dev $interface
 ipset add blocklist [ipaddrs]  ## add [ipaddrs] to blocklist
 ipset create blocklist hash:ip  ## create ip blocklist
 iw dev [wl_interface] scan | grep SSID | sort | uniq  ## received SSID list
@@ -212,9 +212,9 @@ lspci -k -s <xx:xx.x> #[[[[<domain>]:]<bus>]:][<slot>][.[<func>]]
 lspci -kvvt
 lspci -vv  ## list pci devices, find kernel drivers
 man -k . | fzf | awk '{print $1}' | xargs -r env TERM=xterm man  ## fzf find and open manpage
-man ascii  ## 7-bits ascii tables
+man ascii  ## 7-bit ascii tables
 man zshall  ## view the system reference manual for all zsh
-mkdir /dock/<1-4>
+mkdir $HOME/dock/{1-4}  ## make multiple directories
 nmcli connection add type ethernet con-name $con_name ifname $if_name
 nmcli connection modify $con_name ipv4.addresses 192.168.0.39/24 ipv4.gateway 192.168.2.2 ipv4.dns 192.168.2.2 +ipv4.dns 9.9.9.9 connection.autoconnect no ipv4.method manual
 modprobe -r <driver>  ## remove driver from kernel
@@ -228,7 +228,6 @@ mpv --start=+00:00 --ytdl-format='best[filesize<300M]' --profile=cache_xs --demu
 mpv `echo $url | sed 's/https:\/\/www.youtube.com\/watch?v=/https:\/\/youtu.be\//'`  ## change yt url
 mpv --audio-display=no $file.mp3  ## play mp3 without albumart
 mpv /dev/video4  ## livestream local webcam
-msgcat --color=test
 mv -t <target_dir> <source_dirs>  ## move source_dirs to target_dir
 notmuch address '*'  ## all mail addresses
 notmuch address --output=recipients --deduplicate=address date:year | fzf | wl-copy  ## last years recipients
@@ -259,10 +258,10 @@ printf "$tring" | awk '{print $1+0}'  ## awk retrieves the second field as a num
 printf "%03d%s" "2"  ## print leading zeros
 printf "%3d%s" "2"  ## print leading spaces
 printf "%d\n" \'A  ## character (A) to ascii value (65)
-printf "Mime-Version: 1.0; Content-Type: text/plain; charset=us-ascii; Content-Transfer-Encoding: 7bit; Subject: <subject>\n; <body>" | msmtp -v -C <msmtp_config> -a <profile_name> -- destination@mail.com
+printf "Mime-Version: 1.0; Content-Type: text/plain; charset=us-ascii; Content-Transfer-Encoding: 7bit; Subject: <subject>\n; <body>" | msmtp -v -C <msmtp_config> -a <profile_name> -- destination@mail.com  ## send email
 printf "\x$(printf %x 65)"  ## ascii value (65) to character (A)
-printf "space_every_4th_char" | fold -w 4 | paste -sd ' ' -
-printf "space_every_4th_char" | sed 's/.\{4\}/& /g'
+printf "space_every_4th_char" | fold -w 4 | paste -sd ' ' -  ## space every 4th character (with fold)
+printf "space_every_4th_char" | sed 's/.\{4\}/& /g'  ## space every 4th character (with sed)
 printf $(( [#n] x ))  ## print base 10 value of x in base n, with 2<=n<=36
 printf text | openssl dgst -sha512 -hmac key | sed 's/^.*= //' | wl-copy
 ps -ajxf  ## print a process tree
@@ -275,7 +274,6 @@ qbns -s content.canvas_reading true -s content.webgl true -s colors.webpage.dark
 qrencode -t utf8  ## create qr from stdin
 qutebrowser -s content.canvas_reading true ## qb for windy
 rankmirrors -n 10 /etc/pacman.d/mirrorlist | grep -w 'Server =' >> mirrorlist.ranked
-rcvboxdrv
 read input  ## zz1
 read -er input | tr -d '\n' | base64 | tr -d '\n' | wl-copy -n -o; unset input  ## input base64 translation without EOL
 read -er input | base64 | wl-copy -n -o; unset input  ## input base64 translation
@@ -295,10 +293,10 @@ rfkill [un]block bluetooth  ## soft [un]block bluetooth radio
 rfkill [un]block wlan  ## soft [un]block wifi radio
 rm -rf -- '-r'  ## remove entire directory starting with a '-'
 rmmod $module  ## remove $module from linux kernel
-rsync -aAXv --delete --exclude-from=<exclude_list> <source> <destination>
-rsync -aAXv --delete --stats --progress --info=progress2 --modify-window=1 --exclude-from=/home/cytopyge/.config/settings/rsync/parvus_exclude_list / /dock/1/parvus
-rsync -aAXv --delete --stats --progress --info=progress2 --modify-window=1 --exclude-from=/home/cytopyge/settings_/rsync/parvus_exclude_list -e ssh / admin@192.168.3.199:/share/backup/devices/dellxps13
-rsync -aAXv --delete <source> <destination>
+rsync -aAXv --delete --info=progress2 $source/ $destination
+rsync -aAXv --delete --info=progress2 --exclude-from=$exclude.list $source/ $destination
+rsync -aAXv --delete --stats --progress --info=progress2 --modify-window=1 --exclude-from=/home/oxo/.config/settings/rsync/parvus_exclude_list / /dock/1/parvus
+rsync -aAXv --delete --stats --progress --info=progress2 --modify-window=1 --exclude-from=/home/oxo/.config/settings/rsync/parvus_exclude_list -e ssh / admin@192.168.3.199:/share/backup/devices/dellxps13
 rsync -aAXv --dry-run --delete --info=progress2 $XDG_DATA_HOME/c/ $XDG_DATA_HOME/b  ## backup_c2b
 script; command; exit  ## make typescript of command
 sed ':a;N;$!ba;s/\n//g' | sed 's/ //g' | sed 's/\r$//g'  ## remove all spaces from string
@@ -314,19 +312,17 @@ sed -i -n -e :a -e '1,2!{P;N;D;};N;ba' <file>  ## remove last 2 lines from <file
 sed -i '/^find/ s/./#&/' <file>  ## comment out lines containing 'find'
 set -euo pipefail  ## exit on: -e command error, -u unset variable expansion error, -o pipefail
 set -o errexit -o nounset -o pipefail  ## exit on: -e command error, -u unset variable expansion error, -o pipefail
-setfont ter-v32n
+setfont ter-v32n  ## set console font
 setopt interactive_comments  ## threat string after '#' as comment (unsetopt disables)
 sh -xv file.sh  ## extra verbose debug output
 showkey [-a|--ascii] [-s|--scancodes] [-k|--keycodes]  ## examine codes sent by the keyboard
 shred -v -z -n 3 -u <file>
 simple-mtpfs --device 1 <mountpoint>  ## mount android device
-sleep 3 && scrot -s
-slurm -i <device>
 echo 'string2sort' | grep -o . | sort | tr -d "\n"  ## sort chars in string
 sort $HISTFILE | uniq -c | sort -k1,1nr -k2 >> history_freq  ## create history frequency list
-sort < $file | sort -nr > <file_sort_freq>
-sort < $file | uniq -u > <file_uniq>
-sort $file | uniq -c | sort -k1,1nr -k2 | sed 's/^ *[0-9]* //' > file_freq_sort
+sort < $file | sort -nr > $file_sort_freq  ## reverse numerical sort
+sort < $file | uniq -u > $file_uniq  ## unique lines
+sort $file | uniq -c | sort -k1,1nr -k2 | sed 's/^ *[0-9]* //' > file_freq_sort  ## sort columns: k1 numeric reverse then k2
 split $file -b N  ## split $file into files with N bytes
 split $file -l N  ## split $file into files with N lines
 split $file -n N  ## split $file into N files
@@ -354,7 +350,7 @@ swaymsg -t get_tree | jq -r 'recurse(.nodes[], .floating_nodes[]) | select(.shel
 echo '1' | sudo tee /proc/sys/kernel/sysrq  ## # obtain full sysrq priviledges
 sysrq reisub  ## reboot
 sysrq reisuo  ## shutdown
-systemctl --failed
+systemctl --failed  ## failed services
 systemctl isolate graphical.target
 systemctl isolate multi-user.target
 systemctl list-unit-files
@@ -388,11 +384,10 @@ unsetvar=  ## set variable unsetvar to ''
 uptime  ## uptime since boot
 < /proc/uptime | awk '{print $1}'  ## uptime in seconds
 usermod -a -G group_2_add user_2_add  ## add user to group
-vlock -a  ## console lock
-watch -d -n 1 -t lsblk -i --tree -o name,fstype,uuid,path,size,fsuse%,fsused,label,mountpoint
-watch -n 1 'ls -ilatr'
+vlock -a  ## console lock all sessions
+watch -d -n 1 -t lsblk -i --tree -o name,fstype,uuid,path,size,fsuse%,fsused,label,mountpoint  ## watch lsblk
+watch -n 1 'ls -ilatr'  ## watch ls -ilatr
 wev  ## show wayland events i.e. keypresses keynames
-wget -rv -l 0 -nd http://proxpn.com/locations
 which -a <command>  ## show path of all <command> (from $PATH)
 while IFS= read -r pkg; do ls /var/cache/pacman/pkg | grep ^"$pkg"; done <<< "$(pacman -Qm | awk '{print $1}')"  ## which package from Qm is in /v/c/p/p
 while read -r -u $fd l; do <commands>; done {fd}< <file>  ## read file line by line into l (with stdin redirection)
